=== caybcc/Java/XML/WebContent/book.dtd
<!ENTITY bn "JavaWeb">
<!ELEMENT bookself (book+)>
<!ELEMENT book (bookname,author,price)>
<!ELEMENT bookname (#PCDATA)>
<!ELEMENT author (#PCDATA)>
<!ELEMENT price (#PCDATA)>

=== caybcc/Java/XML/WebContent/book.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE bookself SYSTEM "book.dtd">
<bookself>
	<book>
		<bookname>&bn;从入门到放弃</bookname>
		<author>李某某</author>
		<price>￥45.0</price>
	</book>
	<book>
		<bookname>MySQL从删库到跑路</bookname>
		<author>成莫某</author>
		<price>￥65.9</price>
	</book>
</bookself>
